#Création de la base de donnée
CREATE DATABASE plantetagraine;

## 1/ Supprimer les tables inutiles

# Table FOURNISSEUR
# Table RECETTE
# Table MAPPING_RECETTE_GRAINE
# Table MAPPING_FOURNISSEUR_GRAINE

    --> Supprimer les dépendances
ALTER TABLE MAPPING_FOURNISSEUR_GRAINE
DROP FOREIGN KEY MAPPING_FOURNISSEUR_GRAINE_ibfk_1;
DROP FOREIGN KEY MAPPING_FOURNISSEUR_GRAINE_ibfk_2;

ALTER TABLE MAPPING_RECETTE_GRAINE
DROP FOREIGN KEY MAPPING_RECETTE_GRAINE_ibfk_1;
DROP FOREIGN KEY MAPPING_RECETTE_GRAINE_ibfk_2;

ALTER TABLE RECETTE
DROP FOREIGN KEY RECETTE_ibfk_1;


    --> Supprimer les Tables
DROP TABLE FOURNISSEUR
DROP TABLE RECETTE
DROP TABLE MAPPING_RECETTE_GRAINE
DROP TABLE MAPPING_FOURNISSEUR_GRAINE


## 2/ AJOUTER DES COLONNES A CERTAINES TABLES

ALTER TABLE JARDINIER ADD (PHOTO varchar(50),AGE varchar(2),TELEPHONE int);

## 3/ CREATION DE NOUVELLES TABLES

# Création de la table "profil"
#la clé étrangère permet de relier l'identifiant du jardinier à son profil
CREATE TABLE PROFIL (
ID_JARDINIER int,
CENTRES_DINTERETS varchar(100),
QUALITES varchar(100),
VILLE varchar(100),
PRESENTATION text,
FOREIGN KEY (ID_JARDINIER) REFERENCES JARDINIER(ID_JARDINIER)
);

#Création de la table "stock"
#Elle permet de relier la fiche de la graine au stock de graines du jardinier
#(affiché sur son profil)
CREATE TABLE STOCK (
ID_GRAINE int,
ID_JARDINIER int,
NOMBRE_DE_GRAINES int,
FOREIGN KEY (ID_GRAINE) REFERENCES GRAINE(ID_GRAINE),
FOREIGN KEY (ID_JARDINIER) REFERENCES JARDINIER(ID_JARDINIER)
);

#Création de la table "Message"
#Elle va contenir tous les messages privés échangés entre les jardiniers
CREATE TABLE MESSAGE (
ID_MESSAGE int,
ID_JARDINIER int,
SEND_AT datetime,
MESSAGE varchar(140),
PRIMARY KEY (ID_MESSAGE),
FOREIGN KEY (ID_JARDINIER) REFERENCES JARDINIER(ID_JARDINIER)
);

#Création de la table "Communautés"
CREATE TABLE COMMUNAUTES (
ID_COMMUNAUTE int,
ID_JARDINIER int,
ID_GRAINE int,
NOM varchar(30),
CREATE_AT datetime,
PRIMARY KEY (ID_COMMUNAUTE),
FOREIGN KEY (ID_JARDINIER) REFERENCES JARDINIER(ID_JARDINIER),
FOREIGN KEY (ID_GRAINE) REFERENCES GRAINE(ID_GRAINE)
);

#Création de la table "Message communauté".
#Elle va contenir tous les messages échangés dans les communautés
CREATE TABLE MESSAGE_COMMUNAUTE (
ID_MESSAGE_COMMUNAUTE int,
MESSAGE varchar(140),
SEND_AT datetime,
ID_JARDINIER int,
ID_COMMUNAUTE int,
PRIMARY KEY (ID_MESSAGE_COMMUNAUTE),
FOREIGN KEY (ID_JARDINIER) REFERENCES JARDINIER(ID_JARDINIER),
FOREIGN KEY (ID_COMMUNAUTE) REFERENCES COMMUNAUTES(ID_COMMUNAUTE)
);
